export type PublicRoute = {
  path: string;
  eyebrow: string;
  title: string;
  heading: string;
  description: string;
  points: readonly string[];
};

export const PUBLIC_ROUTES: readonly PublicRoute[] = [
  { path: '/providers', eyebrow: 'PROVIDER DIRECTORY', title: 'AI API Providers', heading: 'Every provider, measured on the same surface.', description: 'Browse AI API providers with source-labelled pricing, recent test coverage, coding-agent compatibility and transparent confidence levels.', points: ['Filter by protocol, model family and region', 'Compare published price without presenting it as verified billing', 'See freshness, sample size and corrections on every profile'] },
  { path: '/models', eyebrow: 'MODEL DIRECTORY', title: 'AI Model Directory', heading: 'Start with the model. Then choose the route.', description: 'Compare how canonical AI model families are offered across providers, protocols, price schedules and developer-tool compatibility suites.', points: ['Canonical model mapping', 'Input, output and cache price dimensions', 'Availability and compatibility by provider'] },
  { path: '/benchmarks', eyebrow: 'OPEN BENCHMARKS', title: 'AI API Benchmarks', heading: 'Measurements you can inspect, cite and download.', description: 'Explore versioned AI API benchmark datasets with observation windows, probe regions, request profiles, sample counts and methodology links.', points: ['Permanent report URLs', 'CSV and JSON downloads', 'Published aggregation versions'] },
  { path: '/rankings/cheapest', eyebrow: 'PRICE RADAR', title: 'Cheapest AI API Providers', heading: 'Compare price without hiding the billing assumptions.', description: 'Rank providers by normalized published or observed input, output and cache prices while preserving model and source context.', points: ['Published and observed prices remain separate', 'Price per one million tokens', 'Last-checked source timestamp'] },
  { path: '/rankings/fastest', eyebrow: 'LATENCY RADAR', title: 'Fastest AI API Providers', heading: 'Median speed is useful. Tail latency tells the story.', description: 'Compare time to first token and total latency with explicit probe region, model, request profile, observation window and sample size.', points: ['Median, P95 and P99 latency', 'Same request profile per comparison', 'Region and time-window disclosure'] },
  { path: '/rankings/reliable', eyebrow: 'RELIABILITY RADAR', title: 'Most Reliable AI API Providers', heading: 'Reliability is a window, not a permanent badge.', description: 'Compare recent success rate, throttling and server-error observations without turning a short test into a lifetime guarantee.', points: ['24-hour, 7-day and 30-day windows', '429 and 5xx shown separately', 'Confidence derived from observations'] },
  { path: '/rankings/most-tested', eyebrow: 'EVIDENCE DEPTH', title: 'Most Tested AI API Providers', heading: 'More observations make every conclusion stronger.', description: 'Find providers with the deepest recent test coverage and inspect how automated, community and provider-submitted sources contribute.', points: ['Observation count', 'Independent source count', 'Automatic and community source labels'] },
  { path: '/compatibility/claude-code', eyebrow: 'CLAUDE CODE LAB', title: 'Claude Code API Compatibility', heading: 'Test the workflow Claude Code actually depends on.', description: 'Compare Messages API behavior, streaming, tool use, multi-turn stability, long output and prompt-cache signals across providers.', points: ['Messages API and SSE', 'Tool use and multi-turn', 'Prompt-cache behavior'] },
  { path: '/compatibility/codex', eyebrow: 'CODEX LAB', title: 'Codex API Compatibility', heading: 'Responses API compatibility under real agent behavior.', description: 'Compare Responses API events, streaming, tool calling, long-running request handling and normalized errors for Codex workflows.', points: ['Responses API event sequence', 'Function and tool calling', 'Long-running stability'] },
  { path: '/compatibility/cursor', eyebrow: 'CURSOR LAB', title: 'Cursor API Compatibility', heading: 'Check the model path your editor will actually use.', description: 'Compare OpenAI-compatible chat, model access, streaming, editing workflows and advanced capabilities used by Cursor clients.', points: ['Compatible chat endpoint', 'Streaming and model access', 'Editing workflow checks'] },
  { path: '/doctor', eyebrow: 'PRIVATE ONE-TIME TEST', title: 'Test My AI API', heading: 'One endpoint. A complete compatibility sequence.', description: 'Enter a Base URL, API key, model and target tool to run a bounded private test; credentials are used in memory and never stored.', points: ['No API key persistence', 'SSRF-safe outbound requests', 'Optional anonymous metrics and public reports'] },
  { path: '/submit', eyebrow: 'DIRECTORY APPLICATION', title: 'Submit an AI API Provider', heading: 'Add a provider with sources reviewers can verify.', description: 'Submit a provider website, endpoint, documentation, pricing, status, models, tools and operator contact for independent review.', points: ['Submission does not guarantee listing', 'Published claims stay labelled', 'Review receipt and correction path'] },
  { path: '/methodology', eyebrow: 'METHODOLOGY', title: 'Benchmark Methodology', heading: 'The rules are public before the results appear.', description: 'Read the precise request profiles, probe regions, timeouts, retry behavior, metric formulas, confidence bands and known limitations.', points: ['Reproducible request profiles', 'Versioned formulas', 'Limitations beside every conclusion'] },
  { path: '/data', eyebrow: 'OPEN DATA', title: 'Radar Data and API', heading: 'Build with the evidence behind the pages.', description: 'Download versioned benchmark snapshots as CSV or JSON and use documented read-only API endpoints with provenance and licensing.', points: ['CSV and JSON snapshots', 'Read-only public API', 'Version, provenance and license'] },
  { path: '/agent-doctor', eyebrow: 'LOCAL-FIRST TOOL', title: 'Agent Doctor by NexoToken', heading: 'Keep task evidence and diagnostics on your machine.', description: 'Download the official Agent Doctor releases for local coding-agent diagnostics, bounded context memory and cost evidence.', points: ['Official NexoToken GitHub releases', 'macOS, Windows and Linux artifacts', 'Checksums and local privacy boundary'] },
  { path: '/about', eyebrow: 'ABOUT', title: 'About NexoToken Radar', heading: 'A data product for better AI API decisions.', description: 'Understand why NexoToken operates Radar, how editorial independence works and where the benchmark product ends and the platform begins.', points: ['Clear operating relationship', 'Equal ranking rules', 'Measurements are not endorsements'] },
  { path: '/privacy', eyebrow: 'PRIVACY', title: 'Radar Privacy Policy', heading: 'Credentials are not a dataset.', description: 'Review how one-time tests, anonymous contributions, public reports, submissions, analytics and retention controls handle user data.', points: ['Keys never stored', 'Contribution is opt-in', 'Public reports are revocable'] },
  { path: '/terms', eyebrow: 'TERMS', title: 'Radar Terms of Use', heading: 'Use measurements with their stated limits.', description: 'Review acceptable testing, provider rights, prohibited scanning, data reuse, correction procedures and limitations of benchmark results.', points: ['Authorized testing only', 'No permanent performance guarantees', 'Documented provider appeal process'] },
  { path: '/corrections', eyebrow: 'CORRECTIONS', title: 'Request a Data Correction', heading: 'Challenge a source, result or provider profile.', description: 'Submit evidence for a factual correction, request a controlled retest or appeal a published result through an auditable review flow.', points: ['Evidence-backed correction', 'Controlled retest request', 'Published update history'] },
  { path: '/sponsorship', eyebrow: 'SPONSORSHIP POLICY', title: 'Radar Sponsorship Policy', heading: 'Promotion never changes a benchmark result.', description: 'See how paid placements are labelled, separated from rankings and prevented from modifying scores, confidence or natural ordering.', points: ['Visible Sponsored label', 'Separate inventory', 'No score or rank influence'] },
] as const;

export function publicRoute(path: string): PublicRoute {
  const route = PUBLIC_ROUTES.find((candidate) => candidate.path === path);
  if (!route) throw new Error(`Unknown public route: ${path}`);
  return route;
}
